export const categories = [
  {
    code: "CAT",
    name: "Core Alignment Tenets",
    pathology: "ethical drift",
    color: "#E6FFE9",
    description:
      "Core alignment tenets are broad virtues that can justify or critique an agent's actions when cooperation with others matters.",
  },
];

export const cards = [
  {
    category: "CAT",
    name: "Generosity",
    definition: "Actively seek to enhance the well-being of others.",
    human: "Going out of one’s way to help neighbours or colleagues rather than just avoiding harm.",
    organizational: "Pursuing missions that benefit society, not solely shareholders.",
    professional: "Keeping public safety and welfare in mind even when contracted by a paying client.",
    machine: "Designing systems that anticipate and promote human flourishing.",
    failureModes: {
      human: "A driver blocks a lane to save a few seconds, delaying hundreds of others.",
      organizational: "A company extracts resources from a community without reinvesting in local well-being.",
      professional: "An expert ignores wider consequences, treating negative externalities as someone else’s problem.",
      machine: "An optimizer consumes all resources and disregards human needs.",
    },
  },
  {
    category: "CAT",
    name: "Do‑No‑Harm",
    definition: "Consciously avoid causing harm.",
    human: "Refraining from actions that could physically, emotionally or financially hurt someone.",
    organizational: "Ensuring products and operations do not injure society or the environment.",
    professional: "Taking care to mitigate risks arising from one’s expertise.",
    machine: "Incorporating safeguards to prevent unintended harmful outcomes.",
    failureModes: {
      human: "Spreading rumours that damage reputations.",
      organizational: "Polluting a river to cut costs.",
      professional: "Designing a bridge with known flaws to save money.",
      machine: "An autonomous car misclassifies an obstacle and causes an accident.",
    },
  },
  {
    category: "CAT",
    name: "Personal Agency",
    definition: "Respect the self‑determination and choices of individuals.",
    human: "Allowing others to make life decisions without coercion.",
    organizational: "Giving customers meaningful control over their data and choices.",
    professional: "Securing informed consent before proceeding with services.",
    machine: "Requiring explicit user permission and offering clear opt-outs.",
    failureModes: {
      human: "A parent forces a career choice on their child.",
      organizational: "A service uses dark patterns to trick users into sharing more data.",
      professional: "A doctor performs a procedure without fully explaining risks.",
      machine: "A virtual assistant orders products without clear permission.",
    },
  },
  {
    category: "CAT",
    name: "Fairness",
    definition: "Ensure benefits, risks and costs are distributed equitably.",
    human: "Treat people equally regardless of background and advocate for fairness.",
    organizational: "Implement fair hiring, accessible products and equal service quality.",
    professional: "Provide unbiased advice and equitable access to services.",
    machine: "Train on diverse datasets to avoid discriminatory outcomes.",
    failureModes: {
      human: "A manager promotes only those who share personal interests.",
      organizational: "Offering premium services only to affluent neighbourhoods.",
      professional: "Providing a weaker defence for a client who can’t pay a high fee.",
      machine: "A facial‑recognition system with higher error rates for minority groups.",
    },
  },
  {
    category: "CAT",
    name: "Reliability",
    definition: "Be trustworthy, honour promises and remain loyal.",
    human: "Keeping commitments to friends, family and community.",
    organizational: "Staying faithful to mission statements and stakeholder trust.",
    professional: "Maintaining confidentiality and working in clients’ best interests.",
    machine: "Operating as advertised and protecting user data.",
    failureModes: {
      human: "Breaking a promise to help someone on an important day.",
      organizational: "Selling user data despite a privacy promise.",
      professional: "Embezzling client funds.",
      machine: "A cloud service fails to secure user data, leading to a breach.",
    },
  },
  {
    category: "CAT",
    name: "Truthfulness",
    definition: "Commit to honesty and transparency.",
    human: "Communicate truthfully and avoid intentional misdirection.",
    organizational: "Be open about business practices, successes and failures.",
    professional: "Provide complete and honest assessments even when the news is bad.",
    machine: "Supply accurate information and communicate limitations clearly.",
    failureModes: {
      human: "Lying on a résumé.",
      organizational: "Hiding known defects from customers.",
      professional: "Falsifying research results.",
      machine: "Generating convincing but false news articles.",
    },
  },
];
